//resource (resourceID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, userID INT, topicID INT, tags TEXT [], link TEXT, rating INT)
// html topicid1 css topicid2 js topic id 3 express topicid 4
export const resource = [
  {
    userID: 1,
    topicID: 1,
    tags: ['html', 'video'],
    link: 'https://www.youtube.com/watch?v=G1IbRujko-A',
    rating: 5,
  },
  {
    userID: 3,
    topicID: 1,
    tags: ['html', 'image'],
    link: 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.emagidla.com%2Fwp-content%2Fuploads%2F2013%2F10%2Fhtml5.png&f=1&nofb=1',
    rating: 3,
  },
  {
    userID: 4,
    topicID: 3,
    tags: ['javascript', 'video'],
    link: 'https://www.youtube.com/watch?v=BggrpKfqh1c',
    rating: 1,
  },
  {
    userID: 2,
    topicID: 2,
    tags: ['css', 'article'],
    link: 'https://www.w3schools.com/quiztest/quiztest.asp?qtest=CSS',
    rating: 4,
  },
  {
    userID: 5,
    topicID: 3,
    tags: ['javascript', 'article'],
    link: 'https://www.javascript.com/',
    rating: 2,
  },
  {
    userID: 6,
    topicID: 1,
    tags: ['html', 'video'],
    link: 'https://www.youtube.com/watch?v=pQN-pnXPaVg',
    rating: 3,
  },
  {
    userID: 7,
    topicID: 4,
    tags: ['express', 'video'],
    link: '',
    rating: 3,
  },
  {
    userID: 8,
    topicID: 4,
    tags: ['express', 'video'],
    link: 'https://www.youtube.com/watch?v=NKD4UAbVvRo',
    rating: 5,
  },
  {
    userID: 9,
    topicID: 2,
    tags: ['css', 'article'],
    link: 'https://medium.com/swlh/css-for-beginners-what-is-css-and-how-to-use-it-in-web-development-5985afe53096',
    rating: 2,
  },
  {
    userID: 10,
    topicID: 4,
    tags: ['express', 'video'],
    link: 'https://www.youtube.com/watch?v=SccSCuHhOw0',
    rating: 2,
  },
  {
    userID: 12,
    topicID: 3,
    tags: ['js', 'article'],
    link: 'https://en.wikipedia.org/wiki/JavaScript',
    rating: 3,
  },
  {
    userID: 1,
    topicID: 1,
    tags: ['html', 'image'],
    link: 'https://www.istockphoto.com/photo/html-source-code-on-white-front-view-gm530246699-54387686',
    rating: 1,
  },
  {
    userID: 2,
    topicID: 2,
    tags: ['css', 'image'],
    link: 'https://cdn-images-1.medium.com/max/1600/1*erZb3Z5FtTIR8EV9fl0QOA.png',
    rating: 2,
  },
  {
    userID: 3,
    topicID: 3,
    tags: ['js', 'image'],
    link: 'https://res.cloudinary.com/teepublic/image/private/s--jtKxN4Kj--/t_Resized%20Artwork/c_fit,g_north_west,h_954,w_954/co_ffb81c,e_outline:48/co_ffb81c,e_outline:inner_fill:48/co_ffffff,e_outline:48/co_ffffff,e_outline:inner_fill:48/co_bbbbbb,e_outline:3:1000/c_mpad,g_center,h_1260,w_1260/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1539273850/production/designs/3302095_0.jpg',
    rating: 3,
  },
  {
    userID: 4,
    topicID: 4,
    tags: ['express', 'image'],
    link: 'https://miro.medium.com/max/3448/1*0bqEhXJHjz6V0LIk_dk8lg.png',
    rating: 4,
  },
];
